export default {
  fr: {
    "distant": "distant",
    "local": "local",
    "threads": "fils",
    "thread": "fil",
    "linked": "liés",
    "record": "entrée",
    "history": "historique",
    "copied": "copié",
    "embed": "intégré",
    "source": "source",
    "log": "journal",
    "Nexus not found": "Nexus inconnu",
    "Nexus theme not found": "Thème du Nexus inconnu",
    "Invalid Nexus data": "Données Nexus invalides",
    "No valid thread": "Aucun fil valide",
    "Duplicate thread id": "Identifiant du fil en double",
    "Duplicate linked thread": "Fil lié en double",
    "Invalid linked thread": "Fil lié non valide",
    "Invalid url": "Url non valide",
    "Invalid thread id": "Identifiant de fil non valide",
    "Invalid length": "Longueur non valide",
    "Invalid min length": "Longueur minimal non valide",
    "Invalid max length": "Longueur maximal non valide",
    "Unable to cut string": "Impossible de raccourcir le texte",
    "Invalid timestamp": "Date non valide",
    "Unknown field": "Champ inconnu",
    "Invalid field type": "Type de champ non valide",
    "Field is empty": "Le champ est vide",
    "Unable to extend string": "Impossible de prolonger le texte",
    "Unknown characters limits category":
      "Catégorie de limite de caractères inconnue",
    "Unknown items limits category": "Catégorie de limite d'éléments inconnue",
    "Invalid media type": "Type de media non valide",
  },
};
